Update community_connectors.json
tableau/webdataconnector pull request #475
Opened 2021-12-11 20:10 UTC by badosa

2021-12-12 09:53 UTC, badosa reviewed
There's a missing comma after "}".

2022-03-09 15:35 UTC, theoutlander requested changes

2022-03-09 18:41 UTC, badosa commented on community/community_connectors.json
> +
Comma added.

2022-03-09 18:41 UTC, badosa commented
Comma added

2022-03-10 16:43 UTC, merged

2022-03-10 16:43 UTC, theoutlander commented
Thanks, @badosa!